; Supervisor config file for program(s)
; copy this file into /etc/supervisor/conf.d/ folder

[program:sensorpush-to-influxdb]
command=/home/imaq-pi01/Projects/sensorpush-to-influxdb/Startup_bash
environment=PYTHONUNBUFFERED=1 ; let stdout logged in real time for python app
user=imaq-pi01
autostart=true
autorestart=true
stdout_logfile=/etc/supervisor/logs/sensorpush-to-influxdb_out.log
stderr_logfile=/etc/supervisor/logs/sensorpush-to-influxdb_err.log
